services:
  mongo:
    image: mongo
  redis:
    image: redis
clone:
  git:
    image: alpine/git
    commands:
      - git init
      - echo $USERNAME
      - git remote add origin http://$USERNAME:$PASSWORD@106.14.244.24:3000/BOBO/Backend.git
      - git pull origin master
    secrets: [ username, password ]
pipeline:
#  test:
#    image: taskalive/toolbox
#    environment:
#      - MONGO_URL=mongodb://mongo
#      - SESSION=http://session
#    commands:
#      - pip3 install m3u8
#      - python3 -m unittest
  build:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t bobo/backend:latest .
  deploy:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker rm -f backend || true
      - docker image tag bobo/backend:latest backend:master
      - docker rmi $(docker images | grep "none" | awk '{print $3}') || true
      - >
        docker run -d --restart always --network=bobo
        -v /srv/bobo/backend:/everything -p 8000:8000
        --name backend backend:master
    when:
      branch: master