version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./db/redis:/data

#  minio:
#    image: minio/minio
#    ports:
#      - 9000:9000
#    volumes:
#      - ./db/minio:/data
#    environment:
#      - MINIO_ACCESS_KEY=hqs
#      - MINIO_SECRET_KEY=hqshqshqs
#    command: server /data