site_name: 项目管理|信息系统设计2020-2021春季学期
site_url: http://106.14.244.24:8080/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
  palette:
    primary: black
    accent: light blue

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences


extra_css:
  - stylesheets/extra.css


nav:
  - 基本介绍: index.md
  - 数据设计: design.md
  - 页面设计: frontend.md
